-- =====================================================
-- TASK LIBRARY - FITNESS EXTENDED (110 tasks)
-- =====================================================
-- This seed adds remaining Fitness tasks to reach 150 total
-- Categories: cardio, strength, flexibility, yoga, sports, challenges

USE klaudie;

-- FITNESS - CARDIO (30 tasks)
INSERT INTO task_library (title, description, category, subcategory, difficulty, level_required, bdsm_intensity, duration_minutes, instructions) VALUES
('Běh 1 km', 'Uběhnout 1 kilometr', 'fitness', 'cardio', 'trivial', 1, 'none', 10, 'Rozcvičit se, běžet konstantním tempem, zchladit se.'),
('Chůze 15 minut rychlá', 'Rychlá chůze 15 minut', 'fitness', 'cardio', 'trivial', 1, 'none', 15, 'Rychlé tempo, aktivní paže, udržet tempo.'),
('Běh 2 km', 'Uběhnout 2 kilometry', 'fitness', 'cardio', 'easy', 1, 'none', 15, 'Konstantní tempo, kontrolovat dech.'),
('Jumping jacks 100x', 'Udělat 100 jumping jacks', 'fitness', 'cardio', 'trivial', 1, 'none', 5, 'V sériích po 25, kontrolovat techniku.'),
('Běh 3 km', 'Uběhnout 3 kilometry', 'fitness', 'cardio', 'easy', 2, 'none', 20, 'Udržet konstantní tempo celou dobu.'),
('Cardio intervaly 20 minut', '20 minut intervalového tréninku', 'fitness', 'cardio', 'easy', 2, 'none', 20, 'Střídání vysoké a nízké intenzity.'),
('Běh 5 km', 'Uběhnout 5 kilometrů', 'fitness', 'cardio', 'medium', 2, 'none', 35, 'Středně náročný běh, udržet tempo.'),
('Burpees 50x', 'Udělat 50 burpees', 'fitness', 'cardio', 'easy', 2, 'none', 10, 'V sériích, plná technika každého.'),
('Běh 7 km', 'Uběhnout 7 kilometrů', 'fitness', 'cardio', 'medium', 2, 'none', 45, 'Delší běh, správné tempo a dýchání.'),
('HIIT workout 30 minut', '30 minut HIIT tréninku', 'fitness', 'cardio', 'medium', 3, 'none', 30, 'High-intensity interval training.'),
('Běh 10 km', 'Uběhnout 10 kilometrů', 'fitness', 'cardio', 'hard', 3, 'none', 60, 'Dlouhý běh, správná hydratace.'),
('Mountain climbers 200x', '200 mountain climbers', 'fitness', 'cardio', 'medium', 2, 'none', 10, 'Rychle, udržet pozici prkna.'),
('Běh 15 km', 'Uběhnout 15 kilometrů', 'fitness', 'cardio', 'hard', 3, 'none', 90, 'Velmi dlouhý běh, vytrvalost.'),
('Cardio tabata 20 minut', '20 minut Tabata tréninku', 'fitness', 'cardio', 'hard', 3, 'none', 20, '20s práce, 10s pauza, 8 cyklů.'),
('Běh 20 km', 'Uběhnout 20 kilometrů', 'fitness', 'cardio', 'extreme', 4, 'none', 120, 'Extrémní běh, správná příprava nutná.'),
('Burpees 100x na čas', '100 burpees co nejrychleji', 'fitness', 'cardio', 'hard', 3, 'none', 20, 'Plná síla, co nejrychleji.'),
('Běžecké schody 30 minut', '30 minut běhu po schodech', 'fitness', 'cardio', 'hard', 3, 'none', 30, 'Nahoru rychle, dolů pomalu, opakovat.'),
('Jump rope 1000x', '1000 přeskoků přes švihadlo', 'fitness', 'cardio', 'medium', 2, 'none', 20, 'V sériích, udržet rytmus.'),
('Běh půlmaraton', 'Uběhnout půlmaraton (21 km)', 'fitness', 'cardio', 'extreme', 5, 'none', 150, 'Extrémní výkon, důkladná příprava.'),
('Sprint intervaly 20x', '20 sprintů po 100m', 'fitness', 'cardio', 'hard', 3, 'none', 40, 'Maximální rychlost, aktivní odpočinek.'),
('Běh maraton', 'Uběhnout maraton (42 km)', 'fitness', 'cardio', 'extreme', 5, 'none', 300, 'Ultimate výzva, měsíce přípravy.'),
('Shadow boxing 30 minut', '30 minut shadow boxingu', 'fitness', 'cardio', 'medium', 2, 'none', 30, 'Boxerské pohyby, plná rychlost.'),
('Stairs 500 schodů', 'Vyběhnout 500 schodů', 'fitness', 'cardio', 'hard', 3, 'none', 45, 'Nahoru rychle, počítat schody.'),
('Cycling 20 km', 'Ujet 20 km na kole', 'fitness', 'cardio', 'medium', 2, 'none', 60, 'Konstantní tempo, venku nebo na trenažéru.'),
('Rowing 5000m', 'Veslovat 5000 metrů', 'fitness', 'cardio', 'medium', 3, 'none', 25, 'Na veslařském trenažéru, správná technika.'),
('Swimming 1000m', 'Uplavat 1000 metrů', 'fitness', 'cardio', 'medium', 2, 'none', 30, 'Volný styl nebo kombinace stylů.'),
('Cycling 50 km', 'Ujet 50 km na kole', 'fitness', 'cardio', 'hard', 4, 'none', 150, 'Dlouhá jízda, správná výživa a hydr atace.'),
('Rowing 10000m', 'Veslovat 10000 metrů', 'fitness', 'cardio', 'hard', 4, 'none', 50, 'Dlouhý výkon na trenažéru.'),
('Swimming 2000m', 'Uplavat 2000 metrů', 'fitness', 'cardio', 'hard', 3, 'none', 60, 'Delší plavání, udržet techniku.'),
('Cardio endurance test', '90 minut konstantního cardio', 'fitness', 'cardio', 'extreme', 5, 'none', 90, 'Test vytrvalosti, mix aktivit.'),

-- FITNESS - STRENGTH (30 tasks)
('Kliky 20x', 'Udělat 20 kliků správně', 'fitness', 'strength', 'trivial', 1, 'none', 5, 'Správná technika, celý rozsah pohybu.'),
('Dřepy 30x', 'Udělat 30 dřepů', 'fitness', 'strength', 'trivial', 1, 'none', 5, 'Hluboké dřepy, záda rovná.'),
('Výdrž v plank u 60s', 'Vydržet v prkně 60 sekund', 'fitness', 'strength', 'trivial', 1, 'none', 1, 'Rovné tělo, nepropadat se.'),
('Kliky 50x', 'Udělat 50 kliků', 'fitness', 'strength', 'easy', 2, 'none', 8, 'V sériích pokud potřeba.'),
('Dřepy 100x', 'Udělat 100 dřepů', 'fitness', 'strength', 'easy', 2, 'none', 15, 'Udržet techniku po celou dobu.'),
('Plank 2 minuty', 'Vydržet v prkně 2 minuty', 'fitness', 'strength', 'easy', 2, 'none', 2, 'Stabilní jádro, nedýchat mělce.'),
('Shyby 10x', 'Udělat 10 shybů', 'fitness', 'strength', 'easy', 2, 'none', 5, 'Čistá technika, celý rozsah.'),
('Kliky 100x', 'Udělat 100 kliků', 'fitness', 'strength', 'medium', 3, 'none', 15, 'Rozdělit do sérií, plná technika.'),
('Dřepy 200x', 'Udělat 200 dřepů', 'fitness', 'strength', 'medium', 3, 'none', 25, 'Vysoký počet, udržet formu.'),
('Plank 5 minut', 'Vydržet v prkně 5 minut', 'fitness', 'strength', 'medium', 3, 'none', 5, 'Mentální i fyzická výzva.'),
('Shyby 20x', 'Udělat 20 shybů', 'fitness', 'strength', 'medium', 3, 'none', 10, 'Více shybů, čistá technika.'),
('Lunges 100x', 'Udělat 100 výpadů (50 každou nohu)', 'fitness', 'strength', 'medium', 2, 'none', 15, 'Hluboké výpady, střídání nohou.'),
('Wall sit 5 minut', 'Vydržet v sede u zdi 5 minut', 'fitness', 'strength', 'medium', 2, 'none', 5, 'Kolena v 90°, záda u zdi.'),
('Diamond push-ups 50x', '50 diamond push-ups', 'fitness', 'strength', 'medium', 3, 'none', 10, 'Ruce v diamantu, těžší varianta kliků.'),
('Pistol squats 20x', '20 pistol squats (10 každou nohu)', 'fitness', 'strength', 'hard', 4, 'none', 10, 'Dřep na jedné noze, náročné.'),
('Kliky 200x', 'Udělat 200 kliků', 'fitness', 'strength', 'hard', 4, 'none', 30, 'Vysoký počet, rozdělit do sérií.'),
('Dřepy 300x', 'Udělat 300 dřepů', 'fitness', 'strength', 'hard', 4, 'none', 40, 'Extrémní počet dřepů.'),
('Plank 10 minut', 'Vydržet v prkně 10 minut', 'fitness', 'strength', 'hard', 4, 'none', 10, 'Extrémní výzva jádra.'),
('Shyby 50x', 'Udělat 50 shybů', 'fitness', 'strength', 'hard', 4, 'none', 25, 'Vysoký počet shybů.'),
('Muscle-ups 10x', 'Udělat 10 muscle-ups', 'fitness', 'strength', 'hard', 4, 'none', 10, 'Pokročilé cvičení, síla a technika.'),
('One-arm push-ups 20x', '20 one-arm push-ups (10 každou rukou)', 'fitness', 'strength', 'hard', 4, 'none', 15, 'Extrémně náročné kliky.'),
('Handstand push-ups 20x', '20 kliků ve stoji na rukou', 'fitness', 'strength', 'extreme', 5, 'none', 15, 'Pokročilé, vyžaduje skill a sílu.'),
('Kliky 300x', 'Udělat 300 kliků', 'fitness', 'strength', 'extreme', 5, 'none', 45, 'Ultimate výzva kliků.'),
('Dřepy 500x', 'Udělat 500 dřepů', 'fitness', 'strength', 'extreme', 5, 'none', 60, 'Extrémní počet, mentální výzva.'),
('Shyby 100x', 'Udělat 100 shybů', 'fitness', 'strength', 'extreme', 5, 'none', 50, 'Century shybů.'),
('Pull-ups ladder to 10', 'Rebříček 1-10 shybů a zpět', 'fitness', 'strength', 'hard', 4, 'none', 30, '1 shyb, 2, 3... 10, pak dolů 9, 8... 1.'),
('Burpees pyramid 1-10-1', 'Pyramida burpees od 1 do 10 a zpět', 'fitness', 'strength', 'hard', 4, 'none', 25, '1, 2, 3... 10, 9, 8... 1 burpee.'),
('Full body circuit 50 minut', '50 minut full body strength circuit', 'fitness', 'strength', 'hard', 4, 'none', 50, 'Mix všech cvičení, vysoký objem.'),
('Weighted workout', 'Strength trénink s vahami', 'fitness', 'strength', 'medium', 3, 'none', 45, 'Činky/kettlebells, komplexní cvičení.'),
('Calisthenics advanced session', 'Pokročilá calisthenics session', 'fitness', 'strength', 'extreme', 5, 'none', 60, 'Pokročilá cvičení s vlastní vahou.'),

-- FITNESS - FLEXIBILITY (15 tasks)
('Stretchig 15 minut', 'Protažení celého těla 15 minut', 'fitness', 'flexibility', 'trivial', 1, 'none', 15, 'Postupně protáhnout všechny svalové skupiny.'),
('Splits practice 20 minut', 'Cvičit špagát 20 minut', 'fitness', 'flexibility', 'easy', 2, 'none', 20, 'Postupné roztahování směrem ke šp agátu.'),
('Flexibility routine 30 minut', '30 minut flexibility rutiny', 'fitness', 'flexibility', 'easy', 2, 'none', 30, 'Komplexní protažení všech částí těla.'),
('Hip opening session', 'Session na otevření kyčlí', 'fitness', 'flexibility', 'medium', 2, 'none', 30, 'Zaměření na kyčle a hýždě.'),
('Backbend practice', 'Cvičení prohnutí dozadu', 'fitness', 'flexibility', 'medium', 3, 'none', 25, 'Postupné zvyšování flexibility páteře.'),
('Full splits achievement', 'Dosáhnout plného špagátu', 'fitness', 'flexibility', 'hard', 4, 'none', 45, 'Dlouhé držení v plném roztažení.'),
('Advanced stretching 45 minut', '45 minut pokročilého stretchingu', 'fitness', 'flexibility', 'hard', 3, 'none', 45, 'Intenzivní flexibility work.'),
('Contortion basics', 'Základy kontorze', 'fitness', 'flexibility', 'extreme', 5, 'none', 60, 'Extrémní flexibility cvičení.'),
('Middle splits mastery', 'Zvládnout střední špagát', 'fitness', 'flexibility', 'hard', 4, 'none', 40, 'Nožky do stran, plný špagát.'),
('Bridge hold 5 minut', 'Držet most 5 minut', 'fitness', 'flexibility', 'hard', 4, 'none', 5, 'Vysoký most, dlouhé držení.'),
('Shoulder flexibility work', 'Práce na flexibilitě ramen', 'fitness', 'flexibility', 'medium', 2, 'none', 30, 'Otevírání ramen, mobilita.'),
('Deep stretching session', 'Hluboký stretching celého těla', 'fitness', 'flexibility', 'hard', 3, 'none', 60, 'Velmi intenzivní protahování.'),
('PNF stretching', 'PNF stretching technika', 'fitness', 'flexibility', 'medium', 3, 'none', 30, 'Proprioceptive neuromuscular facilitation.'),
('Flexibility challenge', 'Týdenní flexibility výzva', 'fitness', 'flexibility', 'hard', 3, 'none', 210, 'Každý den 30 minut stretching.'),
('Extreme backbend', 'Extrémní prohnutí dozadu', 'fitness', 'flexibility', 'extreme', 5, 'none', 30, 'Pokročilé backbend pozice.'),

-- FITNESS - YOGA (20 tasks)
('Yoga 15 minut začátečník', '15 minut jemné jógy', 'fitness', 'yoga', 'trivial', 1, 'none', 15, 'Základní asány, klidné tempo.'),
('Sun salutation 5x', '5 pozdravů slunci', 'fitness', 'yoga', 'easy', 1, 'none', 15, 'Klasická sekvence, plynulý pohyb.'),
('Yoga 30 minut', '30minutová yoga session', 'fitness', 'yoga', 'easy', 2, 'none', 30, 'Komplexní praxe různých asán.'),
('Vinyasa flow 45 minut', '45 minut Vinyasa flow', 'fitness', 'yoga', 'medium', 2, 'none', 45, 'Plynulý flow mezi pozicemi.'),
('Hatha yoga hodina', 'Hodina Hatha jógy', 'fitness', 'yoga', 'medium', 2, 'none', 60, 'Klasická Hatha praxe.'),
('Power yoga 45 minut', '45 minut power jógy', 'fitness', 'yoga', 'medium', 3, 'none', 45, 'Intenzivní, fyzicky náročná jóga.'),
('Ashtanga primary series', 'Ashtanga primární série', 'fitness', 'yoga', 'hard', 3, 'none', 90, 'Náročná tradiční série.'),
('Yoga inversions practice', 'Cvičení převrácených pozic', 'fitness', 'yoga', 'hard', 3, 'none', 30, 'Stoj na rukou, hlavě, ramenou.'),
('Headstand 5 minut', 'Držet stoj na hlavě 5 minut', 'fitness', 'yoga', 'hard', 4, 'none', 5, 'Stabilní inverze, kontrolované dýchání.'),
('Handstand 2 minuty', 'Držet stoj na rukou 2 minuty', 'fitness', 'yoga', 'hard', 4, 'none', 2, 'U zdi nebo volně, dlouhé držení.'),
('Hot yoga 60 minut', 'Hodina hot jógy', 'fitness', 'yoga', 'hard', 3, 'none', 60, 'Jóga v horkém prostředí.'),
('Yin yoga 90 minut', '90 minut Yin jógy', 'fitness', 'yoga', 'medium', 2, 'none', 90, 'Pasivní dlouhé držení pozic.'),
('Restorative yoga hodina', 'Hodina restorative jógy', 'fitness', 'yoga', 'easy', 1, 'none', 60, 'Odpočinková, regenerační jóga.'),
('Kundalini yoga', 'Kundalini yoga session', 'fitness', 'yoga', 'medium', 2, 'none', 60, 'Energetická jóga s dechem.'),
('Jivamukti yoga', 'Jivamukti yoga class', 'fitness', 'yoga', 'hard', 3, 'none', 75, 'Fyzicky náročná, duchovní jóga.'),
('Bikram yoga class', '90 minut Bikram jógy', 'fitness', 'yoga', 'extreme', 4, 'none', 90, '26 pozic v horkém prostředí, extrémní.'),
('Yoga nidra session', 'Yoga nidra (yogic sleep)', 'fitness', 'yoga', 'easy', 1, 'none', 45, 'Hluboká relaxace, meditativní.'),
('Pranayama practice 30 minut', '30 minut dechových cvičení', 'fitness', 'yoga', 'easy', 2, 'none', 30, 'Různé pranayama techniky.'),
('Advanced arm balances', 'Pokročilé rovnováhy na rukách', 'fitness', 'yoga', 'extreme', 5, 'none', 45, 'Crow, crane, peacock a další.'),
('108 sun salutations', '108 pozdravů slunci', 'fitness', 'yoga', 'extreme', 5, 'none', 180, 'Meditativní výzva, vysoká vytrvalost.'),

-- FITNESS - SPORTS (5 tasks)
('Tenis 60 minut', 'Hrát tenis hodinu', 'fitness', 'sports', 'medium', 2, 'none', 60, 'Cardio a koordinace, hrát zápas.'),
('Fotbal/basket 90 minut', 'Hrát fotbal nebo basket', 'fitness', 'sports', 'medium', 2, 'none', 90, 'Týmový sport, plná hra.'),
('Badminton 45 minut', 'Hrát badminton', 'fitness', 'sports', 'easy', 2, 'none', 45, 'Rychlá hra, cardio.'),
('Lezení hodinа', 'Indoor/outdoor lezení hodinu', 'fitness', 'sports', 'medium', 3, 'none', 60, 'Síla, koordinace, technika.'),
('Martial arts training', 'Trénink bojových umění', 'fitness', 'sports', 'medium', 3, 'none', 60, 'Karate, judo, MMA apod.'),

-- FITNESS - CHALLENGES (10 tasks)
('Murph workout', 'Murph - legendární CrossFit WOD', 'fitness', 'challenges', 'extreme', 5, 'none', 60, '1mi run, 100 pull-ups, 200 push-ups, 300 squats, 1mi run.'),
('300 workout', 'Spartan 300 workout', 'fitness', 'challenges', 'extreme', 5, 'none', 45, '300 reps různých cvičení, časované.'),
('Deck of cards workout', 'Workout s balíčkem karet', 'fitness', 'challenges', 'hard', 4, 'none', 45, 'Každá karta = cvičení a počet.'),
('100 burpees challenge', '100 burpees co nejrychleji', 'fitness', 'challenges', 'hard', 3, 'none', 20, 'Bez zastavení pokud možno.'),
('1000 rep challenge', '1000 reps různých cvičení', 'fitness', 'challenges', 'extreme', 5, 'none', 90, 'Mix cvičení, celkem 1000 opakování.'),
('Tabata torture', '8 cyklů Tabata hell', 'fitness', 'challenges', 'hard', 4, 'none', 35, 'Extrémně intenzivní Tabata.'),
('Body weight gauntlet', 'Gauntlet test vlastní váhy', 'fitness', 'challenges', 'extreme', 5, 'none', 120, 'Série náročných cvičení bez přestávky.'),
('Endurance test mix', 'Mix endurance výzva', 'fitness', 'challenges', 'extreme', 5, 'none', 180, 'Běh, síla, flexibility - vše dohromady.'),
('Death by burpees', 'Death by burpees protokol', 'fitness', 'challenges', 'hard', 4, 'none', 30, 'Každou minutu +1 burpee, do selhání.'),
('Fitness benchmark test', 'Complete fitness test', 'fitness', 'challenges', 'extreme', 5, 'none', 120, 'Test všech fitness aspektů - cardio, síla, flexibility.');
